producer.bootstrap.servers=localhost:9092
producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
producer.value.serializer=sbp.school.kafka.util.TransactionSerializer
producer.partitioner.class=sbp.school.kafka.util.TransactionPartitioner

producer.acks=all
producer.topic.name=quickstart-sber-demo

producer.retry=PT20S
producer.max-retry=2

consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
consumer.value.deserializer=sbp.school.kafka.util.ChecksumDeserializer
consumer.group.id=transaction-ack-consumer

consumer.enable.auto.commit=false
consumer.auto.offset.reset=latest
consumer.max.poll.records=500
consumer.bootstrap.servers=localhost:9092

consumer.topic.name=checksum
consumer.timeout=PT10S
consumer.interval=PT10S
