bootstrap.servers=localhost:9092
topic.name=quickstart-sber-demo

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=sbp.school.kafka.util.TransactionSerializer
partitioner.class=sbp.school.kafka.util.TransactionPartitioner

acks=0