bootstrap.servers=localhost:9092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=sbp.school.kafka.util.TransactionDeserializer

group.id=consumer
enable.auto.commit=false
auto.offset.reset=earliest
max.poll.records=500

topic.name=quickstart-sber-demo